### PR TITLE
Quick fix for values that has more than two(2) colon(":") 

### PR DESCRIPTION
**Pull request by egncndr**
Affected are the date time values that has multiple colon ":"

### CODE REVIEW

**Comment by egncndr** [comment]
Hello Mark,

It occurs when I get the "Encoded Date" in the General Section. Please see the output below.

Values are retrieve via "general.value("Encoded date")"

Before the fix:
Encoded Date: UTC 2015-06-18 00

After the fix:
Encoded Date: UTC 2015-06-18 00:26:41

File Details:
Dimension : 1920 × 1080
Codecs : H.264, AAC
Duration: 01:05
Audio Channel: 2

Video is taken from OnePlus One

Thanks,
Eugene

**Comment by caprica** [comment]
I have no real issue with your patch, I'm just trying to remember why I did it the way I did it, and why I didn't encounter this problem myself before now.    :-/

**Comment by caprica** [comment]
I committed the fix I mentioned above instead of applying this pull request. But thank you for the report that prompted me to look at this as it was clearly a bug. Feel free to contribute something again if you think there are still problems.

**Comment by egncndr** [comment]
Nice, I'll update my project and will be using the one in the maven central repo.

Thank you for accommodating this minor bug.

**Comment by caprica** [comment]
A bug is a bug and should be fixed! Thanks for the report!

**Pull request closed without merging**
